### ISSUE TITLE
Where can I find the benchmark?

### ISSUE THREAD

**Issue by BKHMSI** [eric11eca/curriculum-ling#1]
Hi,

Are there any updates as to when the benchmark will be released?

Thanks!

**Comment by eric11eca** [comment]
Hi, 

Thanks for reaching out! Sorry, I have been super busy with my internship work, so only had some time recently to release the benchmark. You can either download it from this Github repository: all the datasets are under the benchmark/tasks folder. You can also use the benchmark/tasks_v1.0.0.zip. The benchmark is also available on HuggingFace Hub: [https://huggingface.co/datasets/chenz16/curriculum_benchmark](https://huggingface.co/datasets/chenz16/curriculum_benchmark)

Hope this helps.

**Comment by BKHMSI** [comment]
No worries, thanks Zeming!
